[package]
name = "unborsh"
version = "0.1.0"
edition = "2021"
authors = ["Will Kennedy"]
description = "Tools for analyzing and reverse-engineering Borsh serialized data"
repository = "https://github.com/wkennedy/borsh-schema-utils"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["borsh", "serialization", "analysis", "reverse-engineering", "blockchain"]
categories = ["development-tools", "parser-implementations"]

[dependencies]
borsh = "1.5.0"
hex = "0.4.3"
chrono = "0.4.31"

# CLI dependencies
clap = { version = "4.4.7", features = ["derive"], optional = true }
colored = { version = "3.0.0" , optional = true}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.107"

# Optional dependencies
base64 = { version = "0.21.7", optional = true }

[features]
default = []
cli = ["dep:clap", "dep:colored"]
base64_support = ["dep:base64"]
all = ["cli", "base64_support"]

[dev-dependencies]
borsh-derive = "1.5.0"
anyhow = "1.0.75"

[[bin]]
name = "unborsh"
path = "src/cli/unborsh_cli.rs"
required-features = ["cli"]

[[example]]
name = "basic_analysis"
path = "src/examples/basic_usage.rs"

[lib]
name = "unborsh"
path = "src/lib.rs"